controller_list:
  - name: "left_arm"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - yumi_joint_1_l
      - yumi_joint_2_l
      - yumi_joint_7_l
      - yumi_joint_3_l
      - yumi_joint_4_l
      - yumi_joint_5_l
      - yumi_joint_6_l
  - name: "right_arm"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - yumi_joint_1_r
      - yumi_joint_2_r
      - yumi_joint_7_r
      - yumi_joint_3_r
      - yumi_joint_4_r
      - yumi_joint_5_r
      - yumi_joint_6_r
  - name: "right_gripper"
    type: GripperCommand
    action_ns: gripper_action
    default: true
    parallel: true
    joints:
      - gripper_r_joint
      - gripper_r_joint_m
  - name: "left_gripper"
    type: GripperCommand
    action_ns: gripper_action
    default: true
    parallel: true
    joints:
      - gripper_l_joint
      - gripper_l_joint_m
